error:
  whitelabel:
    enabled: false

amazon:
  associateId: habuma-20
server:
  port: 8080
logging:
  level:
    root: INFO
spring:
  jpa:
    open-in-view: false
    properties:
      hibernate.enable_lazy_load_no_trans: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true